In [1]:
# 导入函数库
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import Functions as f
from satellite import Satellite_angle,TMK,TMO,TMZ
# Update the import path to the correct one
from wuchafenxi0922 import wuchafenxi_py


In [2]:
# 读取数据
df = pd.read_csv('data1.csv')
df

用例ID  卫星编号 厂商类型信息  SCID    遥测代号           遥测名称     物理值  \
0       T769393969644700416  4109    小卫星  4109  TMC542    测控任务表点数(注入)       0   
1       T769393969644700416  4109    小卫星  4109  TMC545        遥测下行异常码  0x4022   
2       T769393969644700416  4109    小卫星  4109  TMC547        注入数据CRC  0xEB91   
3       T769393969644700416  4109    小卫星  4109  TMC546         注入数据计数     192   
4       T769393969644700416  4109    小卫星  4109  TMC541  测控任务表剩余点数(使用)      25   
...                     ...   ...    ...   ...     ...            ...     ...   
100556  T769393969644700416  4109    小卫星  4109  TMC619      接收星务遥测帧计数      82   
100557  T769393969644700416  4109    小卫星  4109  TMC615      加解密加密执行计数     135   
100558  T769393969644700416  4109    小卫星  4109  TMC616      加解密认证生产计数     135   
100559  T769393969644700416  4109    小卫星  4109  TMC617       当前遥测密钥ID     190   
100560  T769393969644700416  4109    小卫星  4109  TMC618       可用遥控密钥ID     190   

         原始值     实际值                 星上时间                 采集时间          设备名称  \
0       0000       0  2025-02-11 03:05:40  2025-02-11 03:05:42  新疆信关站_基站_196   
1       4022  0x4022  2025-02-11 03:05:40  2025-02-11 03:05:42  新疆信关站_基站_196   
2       eb91  0xEB91  2025-02-11 03:05:40  2025-02-11 03:05:42  新疆信关站_基站_196   
3         c0     192  2025-02-11 03:05:40  2025-02-11 03:05:42  新疆信关站_基站_196   
4       0019      25  2025-02-11 03:05:40  2025-02-11 03:05:42  新疆信关站_基站_196   
...      ...     ...                  ...                  ...           ...   
100556    52      82  2025-02-11 02:57:07  2025-02-11 02:57:10  新疆信关站_基站_196   
100557    87     135  2025-02-11 02:57:07  2025-02-11 02:57:10  新疆信关站_基站_196   
100558    87     135  2025-02-11 02:57:07  2025-02-11 02:57:10  新疆信关站_基站_196   
100559  00be     190  2025-02-11 02:57:07  2025-02-11 02:57:10  新疆信关站_基站_196   
100560  00be     190  2025-02-11 02:57:07  2025-02-11 02:57:10  新疆信关站_基站_196   

                        设备SN序列号   基站ID  
0       SG04-DJJZ-AR-2024040015  69892  
1       SG04-DJJZ-AR-2024040015  69892  
2       SG04-DJJZ-AR-2024040015  69892  
3       SG04-DJJZ-AR-2024040015  69892  
4       SG04-DJJZ-AR-2024040015  69892  
...                         ...    ...  
100556  SG04-DJJZ-AR-2024040015  69892  
100557  SG04-DJJZ-AR-2024040015  69892  
100558  SG04-DJJZ-AR-2024040015  69892  
100559  SG04-DJJZ-AR-2024040015  69892  
100560  SG04-DJJZ-AR-2024040015  69892  

[100561 rows x 14 columns]

In [3]:
# 删除只有一个非重复值的列
columns = [col for col in df.columns if df[col].nunique() > 1]
df = df[columns]
df

遥测代号           遥测名称     物理值   原始值     实际值                 星上时间  \
0       TMC542    测控任务表点数(注入)       0  0000       0  2025-02-11 03:05:40   
1       TMC545        遥测下行异常码  0x4022  4022  0x4022  2025-02-11 03:05:40   
2       TMC547        注入数据CRC  0xEB91  eb91  0xEB91  2025-02-11 03:05:40   
3       TMC546         注入数据计数     192    c0     192  2025-02-11 03:05:40   
4       TMC541  测控任务表剩余点数(使用)      25  0019      25  2025-02-11 03:05:40   
...        ...            ...     ...   ...     ...                  ...   
100556  TMC619      接收星务遥测帧计数      82    52      82  2025-02-11 02:57:07   
100557  TMC615      加解密加密执行计数     135    87     135  2025-02-11 02:57:07   
100558  TMC616      加解密认证生产计数     135    87     135  2025-02-11 02:57:07   
100559  TMC617       当前遥测密钥ID     190  00be     190  2025-02-11 02:57:07   
100560  TMC618       可用遥控密钥ID     190  00be     190  2025-02-11 02:57:07   

                       采集时间  
0       2025-02-11 03:05:42  
1       2025-02-11 03:05:42  
2       2025-02-11 03:05:42  
3       2025-02-11 03:05:42  
4       2025-02-11 03:05:42  
...                     ...  
100556  2025-02-11 02:57:10  
100557  2025-02-11 02:57:10  
100558  2025-02-11 02:57:10  
100559  2025-02-11 02:57:10  
100560  2025-02-11 02:57:10  

[100561 rows x 7 columns]

In [4]:
# 把遥测代号和遥测名称合并，用于后续的图表展示
df['遥测'] = df['遥测代号'] + '_' + df['遥测名称']
df = df.drop(['遥测代号', '遥测名称','采集时间'], axis=1)
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\1622899594.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['遥测'] = df['遥测代号'] + '_' + df['遥测名称']


物理值   原始值     实际值                 星上时间                    遥测
0            0  0000       0  2025-02-11 03:05:40    TMC542_测控任务表点数(注入)
1       0x4022  4022  0x4022  2025-02-11 03:05:40        TMC545_遥测下行异常码
2       0xEB91  eb91  0xEB91  2025-02-11 03:05:40        TMC547_注入数据CRC
3          192    c0     192  2025-02-11 03:05:40         TMC546_注入数据计数
4           25  0019      25  2025-02-11 03:05:40  TMC541_测控任务表剩余点数(使用)
...        ...   ...     ...                  ...                   ...
100556      82    52      82  2025-02-11 02:57:07      TMC619_接收星务遥测帧计数
100557     135    87     135  2025-02-11 02:57:07      TMC615_加解密加密执行计数
100558     135    87     135  2025-02-11 02:57:07      TMC616_加解密认证生产计数
100559     190  00be     190  2025-02-11 02:57:07       TMC617_当前遥测密钥ID
100560     190  00be     190  2025-02-11 02:57:07       TMC618_可用遥控密钥ID

[100561 rows x 5 columns]

In [5]:
# 只需要一部分数据，输入需要的遥测名称
columns = ['TMK505', 'TMK506', 'TMK507', 'TMK508', 'TMK509', 'TMK510', 'TMZ148', 'TMZ150', 'TMZ151','TMZ153','TMZ154', 'TMO108', 'TMO109', 'TMO110', 'TMO111', 'TMO112', 'TMO113', 'TMO114', 'TMO115', 'TMZ067', 'TMZ068']
# 查找遥测列中包含columns中的元素的行
filtered_df = df[df['遥测'].notna()]  # First, filter out rows with NaN values in '遥测' column
filtered_df = filtered_df[filtered_df['遥测'].str.contains('|'.join(columns))]
filtered_df

物理值       原始值          实际值                 星上时间  \
205      0.00262295  38400300   0.00262295  2025-02-11 03:05:39   
210     -0.00110137  b7a14001  -0.00110137  2025-02-11 03:05:39   
212      0.00273648  3848529e   0.00273648  2025-02-11 03:05:39   
215       -0.002914  b8555140    -0.002914  2025-02-11 03:05:39   
257     -0.00157553  b7e6ac00  -0.00157553  2025-02-11 03:05:39   
...             ...       ...          ...                  ...   
99903    0.00169237  37f7c71d   0.00169237  2025-02-11 02:57:07   
99906   -0.00102215  b795a700  -0.00102215  2025-02-11 02:57:07   
99925   -0.00181626  b804f54e  -0.00181626  2025-02-11 02:57:07   
100188  50.97000122      13e9  50.97000122  2025-02-11 02:57:07   
100190  13.53999996      054a  13.53999996  2025-02-11 02:57:07   

                             遥测  
205         TMK505_轨道系姿态角EulerX  
210         TMK506_轨道系姿态角EulerY  
212           TMK508_轨道系角速度wbox  
215           TMK509_轨道系角速度wboy  
257         TMK507_轨道系姿态角EulerZ  
...                         ...  
99903         TMK508_轨道系角速度wbox  
99906         TMK509_轨道系角速度wboy  
99925         TMK510_轨道系角速度wboz  
100188  TMZ067_QV1轴1（副面轴）转台绝对位置  
100190  TMZ068_QV1轴2（主面轴）转台绝对位置  

[624 rows x 5 columns]

In [6]:
# 便利遥测数据，把数据填充到类中
def fill_df(filtered_df):
    satellite_angles = []

    # 先把数据表格按照星上时间排序
    filtered_df = filtered_df.sort_values(by='星上时间')
    filtered_df = filtered_df.reset_index(drop=True)

    for index, row in filtered_df.iterrows():#+
        # 以星上时间为索引，当星上时间变化时，把上一个卫星姿态数据加入到列表中
        if satellite_angle.time != row['星上时间'] and satellite_angle.time != None:
            satellite_angles.append(satellite_angle)
            satellite_angle = Satellite_angle()  
        satellite_angle.time = row['星上时间']#+
        if "TMK505" in row['遥测']:
            satellite_angle.tmk.TMK505 = row['实际值']
        elif "TMK506" in row['遥测']:
            satellite_angle.tmk.TMK506 = row['实际值']
        elif "TMK507" in row['遥测']:
            satellite_angle.tmk.TMK507 = row['实际值']
        elif "TMK508" in row['遥测']:
            satellite_angle.tmk.TMK508 = row['实际值']
        elif "TMK509" in row['遥测']:
            satellite_angle.tmk.TMK509 = row['实际值']
        elif "TMK510" in row['遥测']:
            satellite_angle.tmk.TMK510 = row['实际值']
        elif "TMZ148" in row['遥测']:
            satellite_angle.tmz.TMZ148 = row['实际值']
        elif "TMZ150" in row['遥测']:
            satellite_angle.tmz.TMZ150 = row['实际值']
        elif "TMZ151" in row['遥测']:
            satellite_angle.tmz.TMZ151 = row['实际值']
        elif "TMZ153" in row['遥测']:
            satellite_angle.tmz.TMZ153 = row['实际值']
        elif "TMZ154" in row['遥测']:
            satellite_angle.tmz.TMZ154 = row['实际值']
        elif "TMZ067" in row['遥测']:
            satellite_angle.tmz.TMZ067 = row['实际值']
        elif "TMZ068" in row['遥测']:
            satellite_angle.tmz.TMZ068 = row['实际值']
        elif "TMO108" in row['遥测']:
            satellite_angle.tmo.TMO108 = row['实际值']
        elif "TMO109" in row['遥测']:
            satellite_angle.tmo.TMO109 = row['实际值']
        elif "TMO110" in row['遥测']:
            satellite_angle.tmo.TMO110 = row['实际值']
        elif "TMO111" in row['遥测']:
            satellite_angle.tmo.TMO111 = row['实际值']
        elif "TMO112" in row['遥测']:
            satellite_angle.tmo.TMO112 = row['实际值']
        elif "TMO113" in row['遥测']:
            satellite_angle.tmo.TMO113 = row['实际值']
        elif "TMO114" in row['遥测']:
            satellite_angle.tmo.TMO114 = row['实际值']
        elif "TMO115" in row['遥测']:
            satellite_angle.tmo.TMO115 = row['实际值']

In [7]:
# 新建一个表格，序列为星上时间，列为遥测名称，值为实际值
df_pivot = filtered_df.pivot(index="星上时间", columns='遥测', values='实际值')
# 重置索引
df_pivot = df_pivot.reset_index()
df_pivot

遥测                 星上时间 TMK505_轨道系姿态角EulerX TMK506_轨道系姿态角EulerY  \
0   2025-02-11 02:57:07          0.00268256          0.02102503   
1   2025-02-11 02:57:15          0.00330496          0.01553526   
2   2025-02-11 02:57:23          0.00032059          0.01114004   
3   2025-02-11 02:57:31          0.00246154          0.01152936   
4   2025-02-11 02:57:32                 NaN                 NaN   
..                  ...                 ...                 ...   
68  2025-02-11 03:05:07         -0.00297284          -0.0009494   
69  2025-02-11 03:05:15         -0.00343494           0.0003842   
70  2025-02-11 03:05:23         -0.00307182          0.00087256   
71  2025-02-11 03:05:31         -0.00110665          0.00020491   
72  2025-02-11 03:05:39          0.00262295         -0.00110137   

遥测 TMK507_轨道系姿态角EulerZ TMK508_轨道系角速度wbox TMK509_轨道系角速度wboy TMK510_轨道系角速度wboz  \
0           0.00014343        0.00169237       -0.00102215       -0.00181626   
1          -0.00040085        0.00149511       -0.00403465       -0.00102436   
2           0.00101786       -0.00120033        0.00122533       -0.00010389   
3            0.0009892       -0.00103134        0.00250405       -0.00208126   
4                  NaN               NaN               NaN               NaN   
..                 ...               ...               ...               ...   
68         -0.00263208        0.00378081        0.00363525       -0.00050017   
69         -0.00447046        0.00253395        0.00324117       -0.00082776   
70         -0.00422629       -0.00114382        0.00280766        0.00072032   
71         -0.00209239       -0.00241363       -0.00193024       -0.00036226   
72         -0.00157553        0.00273648         -0.002914       -0.00010424   

遥测 TMO108_WGS84短时外推时间秒 TMO109_WGS84短时外推时间微秒 TMO110_WGS84短时外推位置X  ...  \
0                  NaN                  NaN                 NaN  ...   
1                  NaN                  NaN                 NaN  ...   
2                  NaN                  NaN                 NaN  ...   
3                  NaN                  NaN                 NaN  ...   
4        1739213852000                  750        470251.46875  ...   
..                 ...                  ...                 ...  ...   
68                 NaN                  NaN                 NaN  ...   
69                 NaN                  NaN                 NaN  ...   
70                 NaN                  NaN                 NaN  ...   
71                 NaN                  NaN                 NaN  ...   
72                 NaN                  NaN                 NaN  ...   

遥测 TMO113_WGS84短时外推速度X TMO114_WGS84短时外推速度Y TMO115_WGS84短时外推速度Z  \
0                  NaN                 NaN                 NaN   
1                  NaN                 NaN                 NaN   
2                  NaN                 NaN                 NaN   
3                  NaN                 NaN                 NaN   
4         740.66729736        5913.4140625      -4235.90087891   
..                 ...                 ...                 ...   
68                 NaN                 NaN                 NaN   
69                 NaN                 NaN                 NaN   
70                 NaN                 NaN                 NaN   
71                 NaN                 NaN                 NaN   
72                 NaN                 NaN                 NaN   

遥测 TMZ067_QV1轴1（副面轴）转台绝对位置 TMZ068_QV1轴2（主面轴）转台绝对位置 TMZ148_馈电指向时间_秒  \
0              50.97000122             13.53999996             NaN   
1              50.36999893             13.65999985             NaN   
2              49.72000122             13.78999996             NaN   
3              49.04000092             13.92000008       161377051   
4                      NaN                     NaN             NaN   
..                     ...                     ...             ...   
68            -48.59999847              2.77999997             NaN   
69            -4

In [8]:
# 开始提取数据并进行相应计算
# 1. 找到TMZ148出现的时间，找到对应的TMO110~115的值，作为TMO轨道数据
# 只保留TMZ148不为空的行，以及下面一行
notna_index = df_pivot[df_pivot['TMZ148_馈电指向时间_秒'].notna()].index
df_calculate = df_pivot[df_pivot['TMZ148_馈电指向时间_秒'].notna()]

# 找到TMZ148的下一行
next_index = notna_index + 1
df_calculate = pd.concat([df_calculate, df_pivot.loc[next_index]], axis=0)	# 把下一行加入到df_calculate中
# 重置索引,按照星上时间排序
df_calculate = df_calculate.sort_values(by='星上时间')
df_calculate = df_calculate.reset_index(drop=True)
df_calculate

遥测                 星上时间 TMK505_轨道系姿态角EulerX TMK506_轨道系姿态角EulerY  \
0   2025-02-11 02:57:31          0.00246154          0.01152936   
1   2025-02-11 02:57:32                 NaN                 NaN   
2   2025-02-11 02:58:35          0.00065415         -0.03564163   
3   2025-02-11 02:58:36                 NaN                 NaN   
4   2025-02-11 02:59:39         -0.00002044         -0.00550342   
5   2025-02-11 02:59:40                 NaN                 NaN   
6   2025-02-11 03:00:43         -0.00169853          0.00046787   
7   2025-02-11 03:00:44                 NaN                 NaN   
8   2025-02-11 03:01:47         -0.00091845         -0.00246058   
9   2025-02-11 03:01:48                 NaN                 NaN   
10  2025-02-11 03:02:51          0.00193716         -0.01037847   
11  2025-02-11 03:02:52                 NaN                 NaN   
12  2025-02-11 03:03:55          0.00073579         -0.00219078   
13  2025-02-11 03:03:56                 NaN                 NaN   
14  2025-02-11 03:04:59         -0.00204815         -0.00098184   
15  2025-02-11 03:05:00                 NaN                 NaN   

遥测 TMK507_轨道系姿态角EulerZ TMK508_轨道系角速度wbox TMK509_轨道系角速度wboy TMK510_轨道系角速度wboz  \
0            0.0009892       -0.00103134        0.00250405       -0.00208126   
1                  NaN               NaN               NaN               NaN   
2           0.00035101        0.00336061        -0.0003275       -0.00046683   
3                  NaN               NaN               NaN               NaN   
4           0.00251634        0.00264331       -0.00148649       -0.00085956   
5                  NaN               NaN               NaN               NaN   
6           0.00178834       -0.00038066        0.00163428        0.00012758   
7                  NaN               NaN               NaN               NaN   
8           0.00259312       -0.00326535       -0.00119181        0.00059142   
9                  NaN               NaN               NaN               NaN   
10         -0.00149202         0.0037223       -0.00215238       -0.00086141   
11                 NaN               NaN               NaN               NaN   
12         -0.00125313        0.00735706        -0.0023038        0.00121087   
13                 NaN               NaN               NaN               NaN   
14          0.00065858        0.00372331       -0.00244351       -0.00042956   
15                 NaN               NaN               NaN               NaN   

遥测 TMO108_WGS84短时外推时间秒 TMO109_WGS84短时外推时间微秒 TMO110_WGS84短时外推位置X  ...  \
0                  NaN                  NaN                 NaN  ...   
1        1739213852000                  750        470251.46875  ...   
2                  NaN                  NaN                 NaN  ...   
3        1739213916000                  750        518440.21875  ...   
4                  NaN                  NaN                 NaN  ...   
5        1739213980000                  750         567957.0625  ...   
6                  NaN                  NaN                 NaN  ...   
7        1739214044000                  750           618426.75  ...   
8                  NaN                  NaN                 NaN  ...   
9        1739214108000                  750         669539.6875  ...   
10                 NaN                  NaN                 NaN  ...   
11       1739214172000                  750         720731.3125  ...   
12                 NaN                  NaN                 NaN  ...   
13       1739214236000                  750         771665.3125  ...   
14                 NaN                  NaN                 NaN  ...   
15       1739214300000                  750         821917.8125  ...   

遥测 TMO113_WGS84短时外推速度X TMO114_WGS84短时外推速度Y TMO115_WGS84短时外推速度Z  \
0                  NaN                 NaN                 NaN   
1         740.66729736        5913.4140625      -4235.90087891   
2                  NaN                 NaN                 NaN   
3         

In [9]:
# 开始计算
# TMO110~115的值是轨道数据，提取6*3的数据
# 6行数据，每行3个数据，不要空值
TMO110 = df_calculate['TMO110_WGS84短时外推位置X'].dropna()
TMO111 = df_calculate['TMO111_WGS84短时外推位置Y'].dropna()
TMO112 = df_calculate['TMO112_WGS84短时外推位置Z'].dropna()
TMO113 = df_calculate['TMO113_WGS84短时外推速度X'].dropna()
TMO114 = df_calculate['TMO114_WGS84短时外推速度Y'].dropna()
TMO115 = df_calculate['TMO115_WGS84短时外推速度Z'].dropna()

# 6*3的数据

TMO_data = np.array([TMO110, TMO111, TMO112, TMO113, TMO114, TMO115])

TMO_data = TMO_data.T
TMO_data

array([['470251.46875', '4304708.5', '6056419.5', '740.66729736',
        '5913.4140625', '-4235.90087891'],
       ['518440.21875', '4674259.5', '5773527.5', '764.27038574',
        '5631.10302734', '-4601.46923828'],
       ['567957.0625', '5025024.5', '5467815.5', '782.14227295',
        '5326.56201172', '-4948.79394531'],
       ['618426.75', '5355621.5', '5140495', '794.0123291',
        '5001.04492188', '-5276.51269531'],
       ['669539.6875', '5664961', '4792740', '799.81915283',
        '4656.68701172', '-5583.28027344'],
       ['720731.3125', '5951479.5', '4426201.5', '798.99261475',
        '4292.83251953', '-5868.22851562'],
       ['771665.3125', '6214126.5', '4042129.5', '791.59918213',
        '3912.8581543', '-6129.59814453'],
       ['821917.8125', '6451979.5', '3642106.75', '777.41918945',
        '3518.32543945', '-6366.77490234']], dtype=object)

In [10]:
# TMK505~510的值是姿态数据，提取6*3的数据
# 6行数据，每行3个数据，不要空值
TMK505 = df_calculate['TMK505_轨道系姿态角EulerX'].dropna()
TMK506 = df_calculate['TMK506_轨道系姿态角EulerY'].dropna()
TMK507 = df_calculate['TMK507_轨道系姿态角EulerZ'].dropna()

TMK508 = df_calculate['TMK508_轨道系角速度wbox'].dropna()
TMK509 = df_calculate['TMK509_轨道系角速度wboy'].dropna()
TMK510 = df_calculate['TMK510_轨道系角速度wboz'].dropna()

# 6*3的数据
ALPHA_data = np.array([TMK505, TMK506, TMK507])


# W
W_data = np.array([TMK508, TMK509, TMK510])
W_data = W_data.T

print("ALPHA_data:", ALPHA_data)
print("W_data:", W_data)


ALPHA_data: [['0.00246154' '0.00065415' '-0.00002044' '-0.00169853' '-0.00091845'
  '0.00193716' '0.00073579' '-0.00204815']
 ['0.01152936' '-0.03564163' '-0.00550342' '0.00046787' '-0.00246058'
  '-0.01037847' '-0.00219078' '-0.00098184']
 ['0.0009892' '0.00035101' '0.00251634' '0.00178834' '0.00259312'
  '-0.00149202' '-0.00125313' '0.00065858']]
W_data: [['-0.00103134' '0.00250405' '-0.00208126']
 ['0.00336061' '-0.0003275' '-0.00046683']
 ['0.00264331' '-0.00148649' '-0.00085956']
 ['-0.00038066' '0.00163428' '0.00012758']
 ['-0.00326535' '-0.00119181' '0.00059142']
 ['0.0037223' '-0.00215238' '-0.00086141']
 ['0.00735706' '-0.0023038' '0.00121087']
 ['0.00372331' '-0.00244351' '-0.00042956']]


In [11]:
# 获取USER_POS数据
USER_POS = np.array([313437, 4770653, 4208987])

# 获取RV数据
RV = TMO_data.astype(float)

# 获取ALPHA数据,TMK505~507
ALPHA = ALPHA_data.astype(float)

# 获取W数据,TMK508~510
W = W_data.astype(float)

print("ALPHA:", ALPHA)

print("W:", W)


ALPHA: [[ 2.461540e-03  6.541500e-04 -2.044000e-05 -1.698530e-03 -9.184500e-04
   1.937160e-03  7.357900e-04 -2.048150e-03]
 [ 1.152936e-02 -3.564163e-02 -5.503420e-03  4.678700e-04 -2.460580e-03
  -1.037847e-02 -2.190780e-03 -9.818400e-04]
 [ 9.892000e-04  3.510100e-04  2.516340e-03  1.788340e-03  2.593120e-03
  -1.492020e-03 -1.253130e-03  6.585800e-04]]
W: [[-0.00103134  0.00250405 -0.00208126]
 [ 0.00336061 -0.0003275  -0.00046683]
 [ 0.00264331 -0.00148649 -0.00085956]
 [-0.00038066  0.00163428  0.00012758]
 [-0.00326535 -0.00119181  0.00059142]
 [ 0.0037223  -0.00215238 -0.00086141]
 [ 0.00735706 -0.0023038   0.00121087]
 [ 0.00372331 -0.00244351 -0.00042956]]


In [12]:
# 把数据带入进行计算
theta ,phi , rang = wuchafenxi_py(USER_POS, RV, ALPHA, W)

theta, phi, rang

(array([48.98363661, 44.82604152, 32.46254421, 18.12146582, 14.52996347,
        27.61103318, 39.87474924, 47.7659032 ]),
 array([353.6719033 , 350.57067984, 342.87423338, 319.54009947,
        243.34276329, 207.82864031, 197.83086488, 193.65251355]),
 array([1927217.49524996, 1593661.54372539, 1318658.42698443,
        1145241.75378967, 1122441.75415498, 1258491.83054767,
        1510543.22572946, 1830606.08641775]))