In [1]:
# 导入函数库
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import Functions as f
from satellite import Satellite_angle,TMK,TMO,TMZ
# Update the import path to the correct one
from wuchafenxi0922 import wuchafenxi_py


In [2]:
# 读取数据
df = pd.read_csv('data2.csv')
df

用例ID  卫星编号 厂商类型信息  SCID    遥测代号           遥测名称  \
0      T773543105277199104  4099    小卫星  4099  TMC303   控制器电源B切换指令状态   
1      T773543105277199104  4099    小卫星  4099  TMC306  QV解锁4（天线2关）状态   
2      T773543105277199104  4099    小卫星  4099  TMC302   星务功率电源A开指令状态   
3      T773543105277199104  4099    小卫星  4099  TMC313        推进供电关状态   
4      T773543105277199104  4099    小卫星  4099  TMC308  QV解锁2（天线1关）状态   
...                    ...   ...    ...   ...     ...            ...   
62570  T773543105277199104  4099    小卫星  4099  TMY033     QV天线解锁供电状态   
62571  T773543105277199104  4099    小卫星  4099  TMY035      反作用轮B供电状态   
62572  T773543105277199104  4099    小卫星  4099  TMY042     发射相控阵1供电状态   
62573  T773543105277199104  4099    小卫星  4099  TMY037      反作用轮D供电状态   
62574  T773543105277199104  4099    小卫星  4099  TMY034      反作用轮A供电状态   

              物理值   原始值         实际值                 星上时间                 采集时间  \
0               关     0           0  2025-02-22 13:49:28  2025-02-22 13:49:30   
1               关     0           0  2025-02-22 13:49:28  2025-02-22 13:49:30   
2               关     0           0  2025-02-22 13:49:28  2025-02-22 13:49:30   
3               关     0           0  2025-02-22 13:49:28  2025-02-22 13:49:30   
4               关     0           0  2025-02-22 13:49:28  2025-02-22 13:49:30   
...           ...   ...         ...                  ...                  ...   
62570           0  0000           0  2025-02-22 13:44:16  2025-02-22 13:44:17   
62571  1.63760996  00f7  1.63760996  2025-02-22 13:44:16  2025-02-22 13:44:17   
62572  1.63098001  00f6  1.63098001  2025-02-22 13:44:16  2025-02-22 13:44:17   
62573  1.63098001  00f6  1.63098001  2025-02-22 13:44:16  2025-02-22 13:44:17   
62574  1.63098001  00f6  1.63098001  2025-02-22 13:44:16  2025-02-22 13:44:17   

               设备名称                  设备SN序列号   基站ID  
0      新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
1      新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
2      新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
3      新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
4      新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
...             ...                      ...    ...  
62570  新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
62571  新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
62572  新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
62573  新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  
62574  新疆信关站_基站_195  SG04-DJJZ-AR-2024030004  69891  

[62575 rows x 14 columns]

In [3]:
# 删除只有一个非重复值的列
columns = [col for col in df.columns if df[col].nunique() > 1]
df = df[columns]
df

遥测代号           遥测名称         物理值   原始值         实际值  \
0      TMC303   控制器电源B切换指令状态           关     0           0   
1      TMC306  QV解锁4（天线2关）状态           关     0           0   
2      TMC302   星务功率电源A开指令状态           关     0           0   
3      TMC313        推进供电关状态           关     0           0   
4      TMC308  QV解锁2（天线1关）状态           关     0           0   
...       ...            ...         ...   ...         ...   
62570  TMY033     QV天线解锁供电状态           0  0000           0   
62571  TMY035      反作用轮B供电状态  1.63760996  00f7  1.63760996   
62572  TMY042     发射相控阵1供电状态  1.63098001  00f6  1.63098001   
62573  TMY037      反作用轮D供电状态  1.63098001  00f6  1.63098001   
62574  TMY034      反作用轮A供电状态  1.63098001  00f6  1.63098001   

                      星上时间                 采集时间  
0      2025-02-22 13:49:28  2025-02-22 13:49:30  
1      2025-02-22 13:49:28  2025-02-22 13:49:30  
2      2025-02-22 13:49:28  2025-02-22 13:49:30  
3      2025-02-22 13:49:28  2025-02-22 13:49:30  
4      2025-02-22 13:49:28  2025-02-22 13:49:30  
...                    ...                  ...  
62570  2025-02-22 13:44:16  2025-02-22 13:44:17  
62571  2025-02-22 13:44:16  2025-02-22 13:44:17  
62572  2025-02-22 13:44:16  2025-02-22 13:44:17  
62573  2025-02-22 13:44:16  2025-02-22 13:44:17  
62574  2025-02-22 13:44:16  2025-02-22 13:44:17  

[62575 rows x 7 columns]

In [4]:
# 把遥测代号和遥测名称合并，用于后续的图表展示
df['遥测'] = df['遥测代号'] + '_' + df['遥测名称']
df = df.drop(['遥测代号', '遥测名称','采集时间'], axis=1)
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_31120\1622899594.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['遥测'] = df['遥测代号'] + '_' + df['遥测名称']


物理值   原始值         实际值                 星上时间                    遥测
0               关     0           0  2025-02-22 13:49:28   TMC303_控制器电源B切换指令状态
1               关     0           0  2025-02-22 13:49:28  TMC306_QV解锁4（天线2关）状态
2               关     0           0  2025-02-22 13:49:28   TMC302_星务功率电源A开指令状态
3               关     0           0  2025-02-22 13:49:28        TMC313_推进供电关状态
4               关     0           0  2025-02-22 13:49:28  TMC308_QV解锁2（天线1关）状态
...           ...   ...         ...                  ...                   ...
62570           0  0000           0  2025-02-22 13:44:16     TMY033_QV天线解锁供电状态
62571  1.63760996  00f7  1.63760996  2025-02-22 13:44:16      TMY035_反作用轮B供电状态
62572  1.63098001  00f6  1.63098001  2025-02-22 13:44:16     TMY042_发射相控阵1供电状态
62573  1.63098001  00f6  1.63098001  2025-02-22 13:44:16      TMY037_反作用轮D供电状态
62574  1.63098001  00f6  1.63098001  2025-02-22 13:44:16      TMY034_反作用轮A供电状态

[62575 rows x 5 columns]

In [5]:
# 只需要一部分数据，输入需要的遥测名称
columns = ['TMK505', 'TMK506', 'TMK507', 'TMK508', 'TMK509', 'TMK510', 'TMZ148', 'TMZ150', 'TMZ151','TMZ153','TMZ154', 'TMO108', 'TMO109', 'TMO110', 'TMO111', 'TMO112', 'TMO113', 'TMO114', 'TMO115', 'TMZ067', 'TMZ068']
# 查找遥测列中包含columns中的元素的行
filtered_df = df[df['遥测'].notna()]  # First, filter out rows with NaN values in '遥测' column
filtered_df = filtered_df[filtered_df['遥测'].str.contains('|'.join(columns))]
filtered_df

物理值       原始值          实际值                 星上时间  \
726     0.00206272  38170001   0.00206272  2025-02-22 13:49:27   
751    -0.00365404  b885bf00  -0.00365404  2025-02-22 13:49:27   
755     0.00241517  3830cd00   0.00241517  2025-02-22 13:49:27   
757    -0.00019332  b6626e00  -0.00019332  2025-02-22 13:49:27   
758     0.00248113  3835a123   0.00248113  2025-02-22 13:49:27   
...            ...       ...          ...                  ...   
62110   0.00210445  381a0e00   0.00210445  2025-02-22 13:44:15   
62111   0.00109879  37a0df7d   0.00109879  2025-02-22 13:44:15   
62138  -0.00011555  b6075835  -0.00011555  2025-02-22 13:44:15   
62208  39.95999908      0f9c  39.95999908  2025-02-22 13:44:15   
62209  27.86000061      0ae2  27.86000061  2025-02-22 13:44:15   

                            遥测  
726        TMK506_轨道系姿态角EulerY  
751        TMK505_轨道系姿态角EulerX  
755        TMK507_轨道系姿态角EulerZ  
757          TMK509_轨道系角速度wboy  
758          TMK508_轨道系角速度wbox  
...                        ...  
62110      TMK507_轨道系姿态角EulerZ  
62111        TMK508_轨道系角速度wbox  
62138        TMK510_轨道系角速度wboz  
62208  TMZ067_QV1轴1（副面轴）转台绝对位置  
62209  TMZ068_QV1轴2（主面轴）转台绝对位置  

[385 rows x 5 columns]

In [6]:
# 便利遥测数据，把数据填充到类中
def fill_df(filtered_df):
    satellite_angles = []

    # 先把数据表格按照星上时间排序
    filtered_df = filtered_df.sort_values(by='星上时间')
    filtered_df = filtered_df.reset_index(drop=True)

    for index, row in filtered_df.iterrows():#+
        # 以星上时间为索引，当星上时间变化时，把上一个卫星姿态数据加入到列表中
        if satellite_angle.time != row['星上时间'] and satellite_angle.time != None:
            satellite_angles.append(satellite_angle)
            satellite_angle = Satellite_angle()  
        satellite_angle.time = row['星上时间']#+
        if "TMK505" in row['遥测']:
            satellite_angle.tmk.TMK505 = row['实际值']
        elif "TMK506" in row['遥测']:
            satellite_angle.tmk.TMK506 = row['实际值']
        elif "TMK507" in row['遥测']:
            satellite_angle.tmk.TMK507 = row['实际值']
        elif "TMK508" in row['遥测']:
            satellite_angle.tmk.TMK508 = row['实际值']
        elif "TMK509" in row['遥测']:
            satellite_angle.tmk.TMK509 = row['实际值']
        elif "TMK510" in row['遥测']:
            satellite_angle.tmk.TMK510 = row['实际值']
        elif "TMZ148" in row['遥测']:
            satellite_angle.tmz.TMZ148 = row['实际值']
        elif "TMZ150" in row['遥测']:
            satellite_angle.tmz.TMZ150 = row['实际值']
        elif "TMZ151" in row['遥测']:
            satellite_angle.tmz.TMZ151 = row['实际值']
        elif "TMZ153" in row['遥测']:
            satellite_angle.tmz.TMZ153 = row['实际值']
        elif "TMZ154" in row['遥测']:
            satellite_angle.tmz.TMZ154 = row['实际值']
        elif "TMZ067" in row['遥测']:
            satellite_angle.tmz.TMZ067 = row['实际值']
        elif "TMZ068" in row['遥测']:
            satellite_angle.tmz.TMZ068 = row['实际值']
        elif "TMO108" in row['遥测']:
            satellite_angle.tmo.TMO108 = row['实际值']
        elif "TMO109" in row['遥测']:
            satellite_angle.tmo.TMO109 = row['实际值']
        elif "TMO110" in row['遥测']:
            satellite_angle.tmo.TMO110 = row['实际值']
        elif "TMO111" in row['遥测']:
            satellite_angle.tmo.TMO111 = row['实际值']
        elif "TMO112" in row['遥测']:
            satellite_angle.tmo.TMO112 = row['实际值']
        elif "TMO113" in row['遥测']:
            satellite_angle.tmo.TMO113 = row['实际值']
        elif "TMO114" in row['遥测']:
            satellite_angle.tmo.TMO114 = row['实际值']
        elif "TMO115" in row['遥测']:
            satellite_angle.tmo.TMO115 = row['实际值']

In [7]:
# 新建一个表格，序列为星上时间，列为遥测名称，值为实际值
df_pivot = filtered_df.pivot(index="星上时间", columns='遥测', values='实际值')
# 重置索引
df_pivot = df_pivot.reset_index()
df_pivot

遥测                 星上时间 TMK505_轨道系姿态角EulerX TMK506_轨道系姿态角EulerY  \
0   2025-02-22 13:44:15          0.00382619         -0.01936358   
1   2025-02-22 13:44:23          0.00249435         -0.01865154   
2   2025-02-22 13:44:24                 NaN                 NaN   
3   2025-02-22 13:44:31           0.0036105          -0.0159946   
4   2025-02-22 13:44:39          0.00610283         -0.01025212   
5   2025-02-22 13:44:47          0.00153733         -0.00545049   
6   2025-02-22 13:44:55         -0.00069727         -0.00193124   
7   2025-02-22 13:45:03         -0.00228843         -0.00112357   
8   2025-02-22 13:45:11         -0.00329066          0.00131481   
9   2025-02-22 13:45:19         -0.00434912           0.0034612   
10  2025-02-22 13:45:27         -0.00406166          0.00134384   
11  2025-02-22 13:45:28                 NaN                 NaN   
12  2025-02-22 13:45:35         -0.00309888          0.00186635   
13  2025-02-22 13:45:43         -0.00531372          0.00297113   
14  2025-02-22 13:45:51         -0.00744762          0.00576639   
15  2025-02-22 13:45:59         -0.00638233          0.00242301   
16  2025-02-22 13:46:07         -0.00494474         -0.00051739   
17  2025-02-22 13:46:15         -0.00130681         -0.00252888   
18  2025-02-22 13:46:23          0.00442169         -0.00729806   
19  2025-02-22 13:46:31          0.00502942         -0.00693606   
20  2025-02-22 13:46:32                 NaN                 NaN   
21  2025-02-22 13:46:39          0.00678499         -0.00770275   
22  2025-02-22 13:46:47          0.00717185         -0.00599861   
23  2025-02-22 13:46:55          0.00336717         -0.00354145   
24  2025-02-22 13:47:03          0.00131636         -0.00470771   
25  2025-02-22 13:47:11         -0.00107832         -0.00482894   
26  2025-02-22 13:47:19           0.0000825         -0.00613522   
27  2025-02-22 13:47:27          0.00192766         -0.00569296   
28  2025-02-22 13:47:35          0.00199425         -0.00520973   
29  2025-02-22 13:47:36                 NaN                 NaN   
30  2025-02-22 13:47:43          0.00288805         -0.00654161   
31  2025-02-22 13:47:51          0.00519606         -0.01187599   
32  2025-02-22 13:47:59          0.00435227         -0.01355963   
33  2025-02-22 13:48:07          0.00167702          -0.0082816   
34  2025-02-22 13:48:15           0.0008217         -0.00733904   
35  2025-02-22 13:48:23          -0.0008351         -0.00689678   
36  2025-02-22 13:48:31         -0.00108312         -0.00165291   
37  2025-02-22 13:48:39          -0.0022919          -0.0011765   
38  2025-02-22 13:48:40                 NaN                 NaN   
39  2025-02-22 13:48:47         -0.00027977         -0.00148557   
40  2025-02-22 13:48:55         -0.00241597         -0.00100062   
41  2025-02-22 13:49:03         -0.00404523         -0.00107234   
42  2025-02-22 13:49:11         -0.00604701          0.00164778   
43  2025-02-22 13:49:19         -0.00578698          0.00256815   
44  2025-02-22 13:49:27         -0.00365404          0.00206272   

遥测 TMK507_轨道系姿态角EulerZ TMK508_轨道系角速度wbox TMK509_轨道系角速度wboy TMK510_轨道系角速度wboz  \
0           0.00210445        0.00109879       -0.00007384       -0.00011555   
1           0.00097117       -0.00133679       -0.00052917       -0.00001422   
2                  NaN               NaN               NaN               NaN   
3           0.00034642        0.00080434       -0.00115254        0.00128938   
4           0.00222952        0.00498562        0.00002157        0.00161123   
5           0.00086082        0.00077055        -0.0009562        0.00073587   
6          -0.00195034       -0.00143927        0.00025272       -0.00043484   
7           0.00062864       -0.00199416       -0.00076179        0.00038325   
8           0.00092613        0.00037673         0.0007089        0.00093987   
9           0.00015128       -0.00166836        0.00263784       -0.00098313   
10          0.00377475       -0.00084

In [8]:
# 开始提取数据并进行相应计算
# 1. 找到TMZ148出现的时间，找到对应的TMO110~115的值，作为TMO轨道数据
# 只保留TMZ148不为空的行，以及下面一行
notna_index = df_pivot[df_pivot['TMZ148_馈电指向时间_秒'].notna()].index
df_calculate = df_pivot[df_pivot['TMZ148_馈电指向时间_秒'].notna()]

# 找到TMZ148的下一行
next_index = notna_index + 1
df_calculate = pd.concat([df_calculate, df_pivot.loc[next_index]], axis=0)	# 把下一行加入到df_calculate中
# 重置索引,按照星上时间排序
df_calculate = df_calculate.sort_values(by='星上时间')
df_calculate = df_calculate.reset_index(drop=True)
df_calculate

遥测                 星上时间 TMK505_轨道系姿态角EulerX TMK506_轨道系姿态角EulerY  \
0   2025-02-22 13:44:23          0.00249435         -0.01865154   
1   2025-02-22 13:44:24                 NaN                 NaN   
2   2025-02-22 13:45:27         -0.00406166          0.00134384   
3   2025-02-22 13:45:28                 NaN                 NaN   
4   2025-02-22 13:46:31          0.00502942         -0.00693606   
5   2025-02-22 13:46:32                 NaN                 NaN   
6   2025-02-22 13:47:35          0.00199425         -0.00520973   
7   2025-02-22 13:47:36                 NaN                 NaN   
8   2025-02-22 13:48:39          -0.0022919          -0.0011765   
9   2025-02-22 13:48:40                 NaN                 NaN   

遥测 TMK507_轨道系姿态角EulerZ TMK508_轨道系角速度wbox TMK509_轨道系角速度wboy TMK510_轨道系角速度wboz  \
0           0.00097117       -0.00133679       -0.00052917       -0.00001422   
1                  NaN               NaN               NaN               NaN   
2           0.00377475       -0.00084096        -0.0006002        -0.0001719   
3                  NaN               NaN               NaN               NaN   
4             0.001729        0.00023899       -0.00135741       -0.00155661   
5                  NaN               NaN               NaN               NaN   
6          -0.00085249       -0.00031776       -0.00129412        0.00040909   
7                  NaN               NaN               NaN               NaN   
8            0.0000365       -0.00058161        0.00115165       -0.00040006   
9                  NaN               NaN               NaN               NaN   

遥测 TMO108_WGS84短时外推时间秒 TMO109_WGS84短时外推时间微秒 TMO110_WGS84短时外推位置X  ...  \
0                  NaN                  NaN                 NaN  ...   
1        1740203064000                  750      -188352.421875  ...   
2                  NaN                  NaN                 NaN  ...   
3        1740203128000                  750      -162354.671875  ...   
4                  NaN                  NaN                 NaN  ...   
5        1740203192000                  750      -138344.734375  ...   
6                  NaN                  NaN                 NaN  ...   
7        1740203256000                  750         -116620.625  ...   
8                  NaN                  NaN                 NaN  ...   
9        1740203320000                  750      -97490.8671875  ...   

遥测 TMO113_WGS84短时外推速度X TMO114_WGS84短时外推速度Y TMO115_WGS84短时外推速度Z  \
0                  NaN                 NaN                 NaN   
1         419.94470215      -4013.85327148       6119.60449219   
2                  NaN                 NaN                 NaN   
3         391.70425415      -4392.33642578       5853.47167969   
4                  NaN                 NaN                 NaN   
5         358.30389404      -4753.93164062       5563.59423828   
6                  NaN                 NaN                 NaN   
7         319.76980591      -5094.81103516       5253.62109375   
8                  NaN                 NaN                 NaN   
9         277.39590454      -5415.85400391       4921.52441406   

遥测 TMZ067_QV1轴1（副面轴）转台绝对位置 TMZ068_QV1轴2（主面轴）转台绝对位置 TMZ148_馈电指向时间_秒  \
0              38.61000061             28.03000069       162366262   
1                      NaN                     NaN             NaN   
2              24.46999931             28.54000092       162366326   
3                      NaN                     NaN             NaN   
4               4.61999989             26.12999916       162366390   
5                      NaN                     NaN             NaN   
6             -16.54000092             20.09000015       162366454   
7                      NaN                     NaN             NaN   
8             -33.06999969             12.97000027       162366518   
9                      NaN                     NaN             NaN   

遥测 TMZ150_馈电1俯仰角 TMZ151_馈电1方位角 TMZ153_馈电2俯仰角 TMZ154_馈电2方位角  
0    41.75999832  332.2799987

In [9]:
# 开始计算
# TMO110~115的值是轨道数据，提取6*3的数据
# 6行数据，每行3个数据，不要空值
TMO110 = df_calculate['TMO110_WGS84短时外推位置X'].dropna()
TMO111 = df_calculate['TMO111_WGS84短时外推位置Y'].dropna()
TMO112 = df_calculate['TMO112_WGS84短时外推位置Z'].dropna()
TMO113 = df_calculate['TMO113_WGS84短时外推速度X'].dropna()
TMO114 = df_calculate['TMO114_WGS84短时外推速度Y'].dropna()
TMO115 = df_calculate['TMO115_WGS84短时外推速度Z'].dropna()

# 6*3的数据

TMO_data = np.array([TMO110, TMO111, TMO112, TMO113, TMO114, TMO115])

TMO_data = TMO_data.T
TMO_data

array([['-188352.421875', '6210853.5', '4086666', '419.94470215',
        '-4013.85327148', '6119.60449219'],
       ['-162354.671875', '5941748.5', '4469923', '391.70425415',
        '-4392.33642578', '5853.47167969'],
       ['-138344.734375', '5648941', '4835387', '358.30389404',
        '-4753.93164062', '5563.59423828'],
       ['-116620.625', '5333722.5', '5181667.5', '319.76980591',
        '-5094.81103516', '5253.62109375'],
       ['-97490.8671875', '4997255.5', '5507368', '277.39590454',
        '-5415.85400391', '4921.52441406']], dtype=object)

In [10]:
# TMK505~510的值是姿态数据，提取6*3的数据
# 6行数据，每行3个数据，不要空值
TMK505 = df_calculate['TMK505_轨道系姿态角EulerX'].dropna()
TMK506 = df_calculate['TMK506_轨道系姿态角EulerY'].dropna()
TMK507 = df_calculate['TMK507_轨道系姿态角EulerZ'].dropna()

TMK508 = df_calculate['TMK508_轨道系角速度wbox'].dropna()
TMK509 = df_calculate['TMK509_轨道系角速度wboy'].dropna()
TMK510 = df_calculate['TMK510_轨道系角速度wboz'].dropna()

# 6*3的数据
ALPHA_data = np.array([TMK505, TMK506, TMK507])

# W
W_data = np.array([TMK508, TMK509, TMK510])
W_data = W_data.T

print("ALPHA_data:", ALPHA_data)
print("W_data:", W_data)


ALPHA_data: [['0.00249435' '-0.00406166' '0.00502942' '0.00199425' '-0.0022919']
 ['-0.01865154' '0.00134384' '-0.00693606' '-0.00520973' '-0.0011765']
 ['0.00097117' '0.00377475' '0.001729' '-0.00085249' '0.0000365']]
W_data: [['-0.00133679' '-0.00052917' '-0.00001422']
 ['-0.00084096' '-0.0006002' '-0.0001719']
 ['0.00023899' '-0.00135741' '-0.00155661']
 ['-0.00031776' '-0.00129412' '0.00040909']
 ['-0.00058161' '0.00115165' '-0.00040006']]


In [17]:
# 获取USER_POS数据
USER_POS1 = np.array([313437, 4770653, 4208987])
USER_POS2 = np.array([-2973445, 3072904, 4716633])
USER_POS3 = np.array([-2839327, 4679324, 3263596])

# 获取RV数据
RV = TMO_data.astype(float)

# 获取ALPHA数据,TMK505~507
ALPHA = ALPHA_data.astype(float)

# 获取W数据,TMK508~510
W = W_data.astype(float)

print("ALPHA:", ALPHA)

print("W:", W)


ALPHA: [[ 2.494350e-03 -4.061660e-03  5.029420e-03  1.994250e-03 -2.291900e-03]
 [-1.865154e-02  1.343840e-03 -6.936060e-03 -5.209730e-03 -1.176500e-03]
 [ 9.711700e-04  3.774750e-03  1.729000e-03 -8.524900e-04  3.650000e-05]]
W: [[-1.33679e-03 -5.29170e-04 -1.42200e-05]
 [-8.40960e-04 -6.00200e-04 -1.71900e-04]
 [ 2.38990e-04 -1.35741e-03 -1.55661e-03]
 [-3.17760e-04 -1.29412e-03  4.09090e-04]
 [-5.81610e-04  1.15165e-03 -4.00060e-04]]


In [18]:
# 把数据带入进行计算
theta ,phi , rang = wuchafenxi_py(USER_POS1, RV , ALPHA, W)

theta, phi, rang

(array([41.73514156, 31.78641355, 22.43272117, 24.88639845, 35.40978093]),
 array([332.28065722, 318.21896541, 284.16152894, 234.62042212,
        209.33158719]),
 array([1542658.39828443, 1298417.46436216, 1171169.82425919,
        1198173.74511554, 1370144.31219278]))